from importlib.metadata import version as get_version

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

intersphinx_mapping = {
    'python': (' https://docs.python.org/3/', None),
    'asv_runner': ('https://airspeed-velocity.github.io/asv_runner/', None)
}

extensions = [
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinxcontrib.katex',
    'sphinxcontrib.bibtex',
    'autoapi.extension',
]

autoapi_dirs = ['../../asv']
autoapi_add_toc_entry = True
autoapi_keep_files = True
autoapi_ignore = ["*_version*", "*migrations*"]
autoapi_options = [
    "members",
    "undoc-members",
    "private-members",
    # "show-inheritance",
    "show-module-summary",
    "special-members",
    "imported-members",
]

bibtex_bibfiles = ["asv.bib"]
bibtex_default_style = "alpha"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8-sig'

# The root toctree document.
root_doc = 'index'

# General information about the project.
project = u'airspeed velocity'
copyright = u'2013--present, Michael Droettboom, Pauli Virtanen, asv Developers'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.
release: str = get_version("asv")
# The short X.Y.Z version.
version: str = ".".join(release.split('.')[:3])

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = 'obj'

# Warn about all references where the target cannot be found.
nitpicky = True

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'furo'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/swallow.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
