name: flake8 Lint

on:
  workflow_run:
    workflows:
      - "Build"
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "latest"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: ""
          max-line-length: "99"
          path: "src"
        run: flake8 . || true
        